name: context_variable_workflow
on:
    workflow_dispatch
env:
    cloud: aws

jobs:
    context_variable_job:
      runs-on: ubuntu-latest
      steps:
        - name: context variable job
          run: |
            echo "Github Repository is ${{github.repository}}"
            echo "Github Repository actor is ${{github.actor}}"
            echo "Name of job is ${{github.job}}"
            echo "Github Repository owner is ${{github.repository_owner}}"