name: My First Workflow
on:
  push
jobs:
    first_job:
      runs-on: ubuntu-latest
      steps:
      - name: Welcome Message
        run: echo "Happy to Start Learning Github Actions !!"

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Listing files
        run: ls -lart

      - name: Read Content from File
        run: cat README.md
