name: Generate ASCII Artwork
on: 
    push
jobs:
    ascii_artwork:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Install Cowsay Command
        run: sudo apt install cowsay -y
    
      - name: Execute Cowsay Command
        run: cowsay -f elephant "I am big" > cow.txt

      - name: Checking File Exist or not
        run: test -f cow.txt

      - name: Content of files
        run: cat cow.txt

      - name: List files
        run: ls -lart
