name: basic-shell-commands
on: [push]

jobs:
  shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: one-liner-command
        run: echo "Happy Learning GitHub Actions !!!"
      - name: multi-liner-command
        run: |
          node -v
          npm -v
  
  parallel-jobs-macos:
    runs-on: macos-latest
    steps:
      - name: View Software Version
        run: sw_vers

  dependent-job:
    runs-on: windows-latest
    needs: [shell-commands]
    steps:
      - name: Echo String
        run: Write-Output "Hello Swarup Learning Github Actions"