name: Working Directories and shell
on: [push]
defaults:
  run:
    shell: bash
    working-directory: /acttions/shell-commands
jobs:
    display-info-on-linux:
      runs-on: ubuntu-latest
      steps:
        - name: Working Directory Check
          run: |
            pwd
            ls -lart
            echo $GITHUB_SHA
            echo $GITHUB_REPOSITORY

    display-info-on-windows:
      runs-on: windows-latest
      defaults:
        run:
          shell: pwsh
      steps:
        - name: Working Directory Check
          run: |
            Get-Location
            dir
            echo $GITHUB_SHA
            echo $GITHUB_REPOSITORY