name: Working Directories and shell
on: [push]
defaults:
  run:
    shell: bash
jobs:
    display-info-on-linux:
      runs-on: ubuntu-latest
      steps:
        - name: Working Directory Check
          run: |
            pwd
            ls -lart
            echo $GITHUB_SHA
            echo $GITHUB_REPOSITORY

        - name: Change Working Directory
          working-directory: /github/dir
          run: pwd

    display-info-on-windows:
      runs-on: windows-latest
      defaults:
        run:
          shell: pwsh
      steps:
        - name: Working Directory Check
          run: |
            Get-Location
            dir
            echo $GITHUB_SHA
            echo $GITHUB_REPOSITORY